### ISSUE TITLE
[Suggestion] Show only heroes that match the selected alliances

### ISSUE THREAD

**Issue by daniheras** [jvonasek/underlords#3]
I think it might be a good feature to be able to show only the heroes that match the marked alliances.  All of them. Example: if i marked "Demon" and "Demon hunter", only "Terrorblade" should appear.

**Comment by jvonasek** [comment]
Thanks for the suggestion. I am considering adding a checkbox for "exact match" or something like that.

Sometimes you have a lineup in mind that consits of multiple alliances, so you can filter them all, but option to find exact set of heroes based on allinaces is also nice to have.

For now, you can also use the search feature.

For example, if you type "heartless mage", it will find Lich (you can also type "undead mage", for people used to synergies from Dota Auto Chess"

**Comment by jvonasek** [comment]
I implemented a checkbox that allows for exact alliance filtering.
